[project]
name = "testsense"
version = "0.1.0"
description = "A Manufacturing test analysis assistant."
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[project.scripts]
testsense = "testsense:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
